// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package di

import (
	"github.com/tonsV2/todo-go/pgk/configuration"
	"github.com/tonsV2/todo-go/pgk/storage/database"
	"github.com/tonsV2/todo-go/pgk/user"
)

// Injectors from wire.go:

func GetEnvironment() Environment {
	configurationConfiguration := configuration.ProvideConfiguration()
	db := database.ProvideDatabase(configurationConfiguration)
	repository := user.ProvideRepository(db)
	service := user.ProvideService(repository)
	handler := user.ProvideHandler(service)
	environment := ProvideEnvironment(configurationConfiguration, handler)
	return environment
}

// wire.go:

type Environment struct {
	Configuration configuration.Configuration
	UserHandler   user.Handler
}

func ProvideEnvironment(configuration2 configuration.Configuration,

	userHandler user.Handler,
) Environment {
	return Environment{configuration2, userHandler}
}
